name = "nomad"
description = "Commands for deploying applications to Nomad."
version = "0.1.0"
spin_compatibility = ">=1.3"
license = "Apache-2.0"
homepage = "https://github.com/vdice/spin-nomad-plugin"
package = "./target/release/nomad-plugin"
